Homework03
reginazs/cs102 pull request #1
Opened 2020-11-26 09:32 UTC by reginazs

2020-11-29 17:28 UTC, anastasiiaCher requested changes
Прототип и консольная версия работают корректно. В гуи-версии отсутствует запуск. Надо, чтобы запуск был во всех трех версиях.

2020-12-02 14:19 UTC, anastasiiaCher requested changes
Нужно еще подправить буквально две строчки. Тогда все будет работать корректно.

2020-12-02 14:19 UTC, anastasiiaCher commented on homework03/life_gui.py
> +                    pause = True
А что будет, если на данной итерации `pause` уже равно `True`. Как снова запустить игру?

2020-12-02 14:19 UTC, anastasiiaCher commented on homework03/life_gui.py
> +                        pause = True
Тут аналогично про `pause`. Логика должна быть такая: при нажатии на паузу игра входит в сосотояние, обратное текущему.

2020-12-02 19:15 UTC, anastasiiaCher approved these changes
Теперь все работает корректно.

2020-12-05 09:44 UTC, merged

2021-01-06 20:36 UTC, reginazs commented
Доброго времени суток, Анастасия Вадимовна!
Я была бы очень благодарна, если бы Вы нашли время проверить 4-ую и 5-ую
лабораторные работы.
С уважением,
Регина (гр. К3143)