hw10
reginazs/cs102 pull request #20
Opened 2021-10-04 13:28 UTC by reginazs

2021-10-07 09:15 UTC, anastasiiaCher requested changes
Вопрос 1: в конце вы показываете график сигмоиды. Что такое сигмоида? Для чего она нужна? Что по графику можно сказать о вашем классификаторе?
Вопрос 2: какая у вас получилась точность классификации? Постройте график, показывающий разброс значений после классификации.

2021-10-12 15:32 UTC, reginazs commented
1. сигмоида это функция, она является непрерывной, принимает на вход любое вещественное число, а на выходе мы получаем опять же вещественное число, что по сути есть уровень активации нейрона (тут отсутствие активации - 0, а полная активация - 1). по моему графику я могу только сказать, что как минимум на промежутке от х=0.025 до х=0.2 значения у меняются довольно таки быстро, поэтому изменение х повлечет значительное изменение у.

2021-10-12 17:10 UTC, anastasiiaCher commented
> 
> 
>     1. сигмоида это функция, она является непрерывной, принимает на вход любое вещественное число, а на выходе мы получаем опять же вещественное число, что по сути есть уровень активации нейрона (тут отсутствие активации - 0, а полная активация - 1). по моему графику я могу только сказать, что как минимум на промежутке от х=0.025 до х=0.2 значения у меняются довольно таки быстро, поэтому изменение х повлечет значительное изменение у.

Это не совсем то, что от вас хотела услышать, но ладно, пусть будет сдано.

2021-10-12 17:10 UTC, anastasiiaCher approved these changes

2021-10-12 17:20 UTC, merged